### ISSUE TITLE
linestyle generator - 'generator' object has no attribute 'next'

### ISSUE THREAD

**Issue by rtotheb2000** [liuyxpp/mpltex#2]
python 3.6.4
matplotlib 2.2.2
mpltex 0.5.1

I have the following issue

```
ls = mpltex.linestyle_generator()
s = ls.next()
```

raises the following error

`AttributeError: 'generator' object has no attribute 'next'`

related stackoverflow posts:

[itertools-cycle-next](https://stackoverflow.com/questions/5237611/itertools-cycle-next)
[theres-no-next-function-in-a-yield-generator-in-python-3](https://stackoverflow.com/questions/12274606/theres-no-next-function-in-a-yield-generator-in-python-3)

**Comment by schlaicha** [comment]
Hi,

as far as I can see this is an issue due to the incompatibility between Python2 and 3, related to #1 (and also explained in the links you posted).
I just solved this by switching back to Python2.

Hope this helps as temporary workaround.

**Comment by schlaicha** [comment]
I just added a fix using the `__next__()`

 iterators in #3.

**Comment by liuyxpp** [comment]
@schlaicha Thanks! I will review this ASAP. Till now I only use Python 2. Maybe it is the time to switch to 3.

**Comment by liuyxpp** [comment]
Issue resovled with version 0.6. Thanks @schlaicha @mighelone.
