### ISSUE TITLE
Cannot use logarithm scale(ax.set_yscale("log")) with Jupyter Lab inline figure

### ISSUE THREAD

**Issue by Chenghao-Wu** [liuyxpp/mpltex#4]
Cannot use logarithm scale(ax.set_yscale("log")) under @mpltex.acs_decorator or mpltex.aps_decorator.

It gives me errors about latex:
"latex was not able to process the following string:
b'$\\\\mathdefault{3\\\\times10^{3}}$'"

**Comment by liuyxpp** [comment]
I have tested most latest version (mpltex 0.6.1), and it seems OK. Please use the attached test case to test your environment. I guess it is the setup of your LaTeX.

[test.zip](https://github.com/liuyxpp/mpltex/files/3376586/test.zip)

**Comment by Chenghao-Wu** [comment]
Thanks for your test files. It is my fault that I didn't make my question clear.

I am using jupyter lab for plotting and the error information I met above was shown in that case. Actually, I can save the figure of the logarithm plot but there is still error information that just messes up the jupyter lab web.

If you have any idea, I would greatly appreciate. 

Thanks for your time.

**Comment by liuyxpp** [comment]
I can reproduce this issue now. However, I have no idea how to fix it.

As a workaround, I found it is possible to remove the error by repeating the plot action for at least 3 times. Then the behavior goes normal.

I highly suspect that the LaTeX preamable generated by matplotlib (which defines \mathdefault) doesn't pass to LaTeX engine for some reason.
